version: '3.1'

services:

  db:
    image: groonga/pgroonga:2.2.7-alpine-13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SECRET
      POSTGRES_DB: testdb
    ports:
      - 5432:5432

  dbsetup:
    image: groonga/pgroonga:2.2.7-alpine-13
    depends_on:
      - db
    restart: "no"
    entrypoint: ["bash", "-c", "until pg_isready -h db -p 5432 -U postgres; do echo 'Wating for postgres...' && sleep 1; done; echo 'Postgres up and ready'; PGPASSWORD=SECRET psql -h db -U postgres -d testdb -c 'create extension pgroonga;'"]